#!/usr/bin/env ruby

require 'bundler/setup'

require_relative '../config/initializers/active_record'

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

unshift_path = lambda { |path|
  p = File.expand_path("../../#{path}", __FILE__)
  $LOAD_PATH.unshift(p) unless $LOAD_PATH.include?(p)
}
unshift_path.call('lib')

require 'obsidian'

exit(Obsidian::ErrorHandler.call do
  Obsidian::EntryPoint.call(ARGV.dup)
end)
